language: java

deploy:
  # deploy to Github
  provider: releases
  api_key:
    secure: owRH6NMMJeFG0kASHk6YI0JkwifNLX4KKPRMjnWqG6TOpsl5gSrKVbeH3iDmYNz1ngDYc3V0NHNPY7gwOh9rscj0lJc0fibmN6v4QuQqgE0fm4tuCsbopdscuDnK2O51H5zovbA0QCzvb1HC0HBgOXLrpUi2QbJH4yL8Z8u6JEcnFFIu9X5W2Slgm12DncbknAJVq8Rp+i3vmTN9HuQBLtN98V77FTGBsTu7ahYbMWcDqJYqHmabeGHeD+4PBdCGp2o1qTAocvpcbKZv7gZdVfUxXG/Nq+0H5imnkfWhjO+tyBEv8tRu+OYH/fc9anITrLLARenQTrs+brVW7rh6IoH/LFtm9A6cnblbZtpLgZLNoKmGrXsaF1/WytoanWz3IsUKSu7IQTuji9ZGRYeYg0X2Z2E5w2EQBCsrDeJkv5OLV/Qvl2y9UvN35uFt72pGaEq4uqO5o0TlsiaYKZ139tG1G23aKRWi15r4V0dLpF1lTmr+yRqb5DT0at8OKQAiyQ+N9ND0k6/thHV4FDiz+sNRkK9UGvhICPJ5XQBlRZJJ1rCURAMX5AuGSUTAyt+DILujZcSH7TSNQdcwifEuYI9OfqoEHTQXDMVU+ZZwiZJmoDExk7L+AzVmV76eke9+wykdTZ+pCa03eYLnQLQdZbbOXf95ySKlmYV8jVJyHmk=
  file_glob: true
  file: "./build/libs/jwebassembly-api-*.jar"
  skip_cleanup: true
  overwrite: true
  on:
    repo: i-net-software/JWebAssembly-API
    tags: true

after_deploy:
  - gradle bintrayUpload
